# vim: ts=2 sw=2

name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Cache nix environment
      run: nix-shell --run "exit 0"
    - name: Build target and test
      run: |
        [[ ! $(git diff --name-only HEAD^ -- | grep "/tests/" | grep -v "lab8/tests/") ]]
        cmake -B build -DCMAKE_BUILD_TYPE=Debug
        cmake --build build -j
        ctest --test-dir build --timeout 120 -T memcheck
        [[ -z $(cat build/Testing/Temporary/MemoryChecker.*.log) ]]
      shell: env nix-shell --run "bash -e {0}"
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: fail-logs
        path: build/Testing/
